### ISSUE TITLE
what is the labels of casia webface dataset

### ISSUE THREAD

**Issue by Pattaro** [wujiyang/Face_Pytorch#36]
i am so sorry to ask for this easy question.....
but i dont know what the labels of casia webface dataset is..... and i dont know how to use it....

**Comment by wujiyang** [comment]
@Pattaro  All these loss functions are margin-based classification, so data label is same as image classification task

**Comment by ruabuliuqiu** [comment]
> i am so sorry to ask for this easy question.....
> but i dont know what the labels of casia webface dataset is..... and i dont know how to use it....

me too

**Comment by QuasarLight** [comment]
> > i am so sorry to ask for this easy question.....
> > but i dont know what the labels of casia webface dataset is..... and i dont know how to use it....
> 
> me too

Maybe you can use my project https://github.com/QuasarLight/Pytorch_Face_Recognition-

**Comment by ruabuliuqiu** [comment]
> > > i am so sorry to ask for this easy question.....
> > > but i dont know what the labels of casia webface dataset is..... and i dont know how to use it....
> > 
> > 
> > me too
> 
> Maybe you can use my project https://github.com/QuasarLight/Pytorch_Face_Recognition-

用了你的generate_dataset_list.py，生成了.list文件，但是报错了，不晓得啥原因

**Comment by QuasarLight** [comment]
> > > > i am so sorry to ask for this easy question.....
> > > > but i dont know what the labels of casia webface dataset is..... and i dont know how to use it....
> > > 
> > > 
> > > me too
> > 
> > 
> > Maybe you can use my project https://github.com/QuasarLight/Pytorch_Face_Recognition-
> 
> 用了你的generate_dataset_list.py，生成了.list文件，但是报错了，不晓得啥原因

Can you send me the error you get?

**Comment by ruabuliuqiu** [comment]
> > > > > i am so sorry to ask for this easy question.....
> > > > > but i dont know what the labels of casia webface dataset is..... and i dont know how to use it....
> > > > 
> > > > 
> > > > me too
> > > 
> > > 
> > > Maybe you can use my project https://github.com/QuasarLight/Pytorch_Face_Recognition-
> > 
> > 
> > 用了你的generate_dataset_list.py，生成了.list文件，但是报错了，不晓得啥原因
> 
> Can you send me the error you get?

/root/anaconda3/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:123: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Train Epoch: 1/80 ...
Traceback (most recent call last):
  File "train_center.py", line 271, in <module>
    train(args)
  File "train_center.py", line 146, in train
    output = margin(feature)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'label'
