### ISSUE TITLE
您好，请问可以提供您所使用的CASIA-WebFace吗？

### ISSUE THREAD

**Issue by satakiolo** [wujiyang/Face_Pytorch#5]
我使用自己的CASIA-WebFace的准确率只有98%，想试试您的

**Comment by wujiyang** [comment]
@satakiolo 稍后我会放到百度云

**Comment by wujiyang** [comment]
@satakiolo    
链接：https://pan.baidu.com/s/1eMpfz2jCbZR2XO91hgFnDA    
提取码：l2zk

**Comment by satakiolo** [comment]
太谢谢您了！

**Comment by satakiolo** [comment]
> @satakiolo
> 链接：https://pan.baidu.com/s/1eMpfz2jCbZR2XO91hgFnDA
> 提取码：l2zk



> @satakiolo 稍后我会放到百度云

作者您好，请问SEResNet50-IR_2只是将SEResNet50-IR再计算了一次？还是有其他意义呢？

**Comment by wujiyang** [comment]
那个可以忽略

**Comment by tiandunx** [comment]
厉害厉害

**Comment by yoyohonyang** [comment]
您好，我看您代码里还使用了一个.list文件，这个list是自己组织的还是数据库自带的呢？可以分享一下这个list文件么？谢谢了！

**Comment by wujiyang** [comment]
@yoyohonyang  自己生成自己训练数据的列表就好了

**Comment by AIrocker** [comment]
@wujiyang  Hi  could you please share us the .list file along with your CASIA-WebFace dataset ?

**Comment by ZZH2950228** [comment]
我生成自己数据集的列表txt文件，但是运行train文件出现下面的错误，请问您是怎么解决的
呢？
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    train(args)
  File "train.py", line 59, in train
    trainset = CASIAWebFace(args.train_root, args.train_file_list, transform=transform)
  File "/home/zzh/桌面/Face_Pytorch-master/dataset/casia_webface.py", line 42, in __init__
    image_path, label_name = info.split(' ')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by swuxyj** [comment]
> @wujiyang Hi could you please share us the .list file along with your CASIA-WebFace dataset ?
Maybe you can try try:
```
import os

with open('webface_align_train.list', 'w') as f:
    root_path = "webface_align_112"
    for index, current_dir in enumerate(os.listdir(root_path)):
        for file in os.listdir(os.path.join(root_path, current_dir)):
            f.write(os.path.join(current_dir, file) + " " + str(index) + "\n")

```

**Comment by jilner** [comment]
你好，请问这个是已经对齐的人脸数据集么，谢谢

**Comment by Tracy-git** [comment]
> 

because you use that generate_data_list.py , has two space （'  '） between path and label 
so you should modify code as:
        for info in img_label_list:
            image_path, label_name = info.split('  ')
            image_list.append(image_path)
            label_list.append(int(label_name))
