### ISSUE TITLE
Visdom successfully connected to server '>' not supported between instances of 'float' and 'NoneType' Traceback (most recent call last):   File "e:/AI-pro/Insightface/Face_Pytorch-master/train_my.py", line 263, in <module>     train(args)   File "e:/AI-pro/Insightface/Face_Pytorch-master/train_my.py", line 155, in train     total_loss.backward()   File "C:\Users\Administrator\Anaconda3\lib\site-packages\torch\tensor.py", line 107, in backward     torch.autograd.backward(self, gradient, retain_graph, create_graph)   File "C:\Users\Administrator\Anaconda3\lib\site-packages\torch\autograd\__init__.py", line 93, in backward     allow_unreachable=True)  # allow_unreachable flag RuntimeError: cuda runtime error (59) : device-side assert triggered at C:/w/1/s/windows/pytorch/aten/src\THC/generic/THCTensorMath.cu:26

### ISSUE THREAD

**Issue by smartparrot** [wujiyang/Face_Pytorch#50]
When I ran train.py, I got the error. Who knows why and how to solve it?

**Comment by smartparrot** [comment]
I figured it out. Some images in my data is wrong, num_workers should be 0 in  dataloader parameters.

**Comment by trantrungpixta** [comment]
I already set num_workers=0, and I've checked my data as well. There is no error. Could it be the problem of env?
